### ISSUE TITLE
"Cannot use luya\admin\Module as Module because the name is already in use"

### ISSUE THREAD

**Issue by cebe** [luyadev/luya-module-admin#116]
getting this error after upgrading from stable to dev:

```
$ composer update
The "extra.asset-installer-paths" option is deprecated, use the "config.fxp-asset.installer-paths" option
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 6 updates, 0 removals                                                    
  - Removing luyadev/luya-module-admin (1.1.1.3)
  - Installing luyadev/luya-module-admin (dev-master 9e2f980): Cloning 9e2f9809c6
  - Removing luyadev/luya-module-cms (1.0.3)
  - Installing luyadev/luya-module-cms (dev-master cb4cd80): Cloning cb4cd80d8a
  - Updating curl/curl (1.8.0 => 1.9.0): Downloading (100%)         
  - Updating luyadev/luya-core (1.0.6 => 1.0.7): Downloading (100%)         
  - Removing luyadev/luya-testsuite (1.1.0)
  - Installing luyadev/luya-testsuite (1.1.x-dev 96e1a48): Cloning 96e1a4823a
  - Updating yiisoft/yii2-gii (2.0.6 => 2.0.7): Downloading (100%)         
Writing lock file
Generating autoload files
```
the error:
```
yii\base\ErrorException: Cannot use luya\admin\Module as Module because the name is already in use in /home/cebe/dev/cebe.cc/luya/vendor/luyadev/luya-module-admin/src/base/RestActiveController.php:11
Stack trace:
#0 /home/cebe/dev/cebe.cc/luya/vendor/luyadev/luya-module-admin/src/ngrest/base/NgRestModel.php(79): Composer\Autoload\ClassLoader->loadClass()
#1 /home/cebe/dev/cebe.cc/luya/vendor/luyadev/luya-module-admin/src/ngrest/base/NgRestModel.php(79): ::spl_autoload_call()
#2 /home/cebe/dev/cebe.cc/luya/vendor/luyadev/luya-module-admin/src/ngrest/base/NgRestModel.php(562): luya\cms\models\Layout->scenarios()
#3 /home/cebe/dev/cebe.cc/luya/vendor/luyadev/luya-module-admin/src/ngrest/base/NgRestModel.php(630): luya\cms\models\Layout->ngRestConfigDefine()
#4 /home/cebe/dev/cebe.cc/luya/vendor/luyadev/luya-module-admin/src/ngrest/base/NgRestModel.php(653): luya\cms\models\Layout->ngRestConfig()
#5 /home/cebe/dev/cebe.cc/luya/vendor/luyadev/luya-module-admin/src/ngrest/base/NgRestModel.php(64): luya\cms\models\Layout->getNgRestConfig()
#6 /home/cebe/dev/cebe.cc/luya/vendor/yiisoft/yii2/base/Component.php(733): luya\cms\models\Layout->behaviors()
#7 /home/cebe/dev/cebe.cc/luya/vendor/yiisoft/yii2/base/Component.php(603): luya\cms\models\Layout->ensureBehaviors()
#8 /home/cebe/dev/cebe.cc/luya/vendor/yiisoft/yii2/db/BaseActiveRecord.php(925): luya\cms\models\Layout->trigger()
#9 /home/cebe/dev/cebe.cc/luya/vendor/yiisoft/yii2/base/BaseObject.php(109): luya\cms\models\Layout->init()
#10 /home/cebe/dev/cebe.cc/luya/vendor/yiisoft/yii2/db/BaseActiveRecord.php(1207): luya\cms\models\Layout->__construct()
#11 /home/cebe/dev/cebe.cc/luya/vendor/yiisoft/yii2/db/ActiveQueryTrait.php(121): yii\db\BaseActiveRecord::instantiate()
#12 /home/cebe/dev/cebe.cc/luya/vendor/yiisoft/yii2/db/ActiveQuery.php(207): yii\db\ActiveQuery->createModels()
#13 /home/cebe/dev/cebe.cc/luya/vendor/yiisoft/yii2/db/ActiveQuery.php(294): yii\db\ActiveQuery->populate()
#14 /home/cebe/dev/cebe.cc/luya/vendor/yiisoft/yii2/db/ActiveRelationTrait.php(184): yii\db\ActiveQuery->one()
#15 /home/cebe/dev/cebe.cc/luya/vendor/yiisoft/yii2/db/BaseActiveRecord.php(299): yii\db\ActiveQuery->findFor()
#16 /home/cebe/dev/cebe.cc/luya/vendor/luyadev/luya-module-cms/src/models/NavItemPage.php(145): luya\cms\models\NavItemPage->__get()
#17 /home/cebe/dev/cebe.cc/luya/vendor/luyadev/luya-module-cms/src/frontend/base/Controller.php(75): luya\cms\models\NavItemPage->getContent()
#18 /home/cebe/dev/cebe.cc/luya/vendor/luyadev/luya-module-cms/src/frontend/controllers/DefaultController.php(71): luya\cms\frontend\controllers\DefaultController->renderItem()
#19 /home/cebe/dev/cebe.cc/luya/vendor/yiisoft/yii2/base/InlineAction.php(57): luya\cms\frontend\controllers\DefaultController->actionIndex()
#20 /home/cebe/dev/cebe.cc/luya/vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/home/cebe/dev/cebe.cc/luya/vendor/yiisoft/yii2/base/InlineAction.php:57}()
#21 /home/cebe/dev/cebe.cc/luya/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#22 /home/cebe/dev/cebe.cc/luya/vendor/yiisoft/yii2/base/Module.php(528): luya\cms\frontend\controllers\DefaultController->runAction()
#23 /home/cebe/dev/cebe.cc/luya/vendor/yiisoft/yii2/web/Application.php(103): luya\web\Application->runAction()
#24 /home/cebe/dev/cebe.cc/luya/vendor/luyadev/luya-core/web/Application.php(47): luya\web\Application->handleRequest()
#25 /home/cebe/dev/cebe.cc/luya/vendor/yiisoft/yii2/base/Application.php(386): luya\web\Application->handleRequest()
#26 /home/cebe/dev/cebe.cc/luya/vendor/luyadev/luya-core/base/Boot.php(221): luya\web\Application->run()
#27 /home/cebe/dev/cebe.cc/luya/vendor/luyadev/luya-core/base/Boot.php(165): luya\Boot->applicationWeb()
#28 /home/cebe/dev/cebe.cc/luya/public_html/index.php(8): luya\Boot->run()
#29 {main}
```

**Comment by cebe** [comment]
going to send a PR.

**Comment by nadar** [comment]
Thanks. Not sure why this appears, as the Module definition is not used in an other place.
