### ISSUE TITLE
proxy command foreign key check

### ISSUE THREAD

**Issue by nadar** [luyadev/luya-module-admin#229]
exception with foreign key checks

```
Exception 'yii\db\Exception' with message 'Error while sending QUERY packet. PID=352
The SQL being executed was: SET FOREIGN_KEY_CHECKS = 1;'

in /app/vendor/yiisoft/yii2/db/Schema.php:664

Stack trace:
#0 /app/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(yii\base\ErrorException), 'SET FOREIGN_KEY...')
#1 /app/vendor/yiisoft/yii2/db/Command.php(1075): yii\db\Command->internalExecute('SET FOREIGN_KEY...')
#2 /app/vendor/luyadev/luya-module-admin/src/proxy/ClientTable.php(181): yii\db\Command->execute()
#3 /app/vendor/luyadev/luya-module-admin/src/proxy/ClientTable.php(138): luya\admin\proxy\ClientTable->cleanup('ONLY_FULL_GROUP...')
#4 /app/vendor/luyadev/luya-module-admin/src/proxy/ClientTransfer.php(41): luya\admin\proxy\ClientTable->syncData()
#5 /app/vendor/luyadev/luya-module-admin/src/commands/ProxyController.php(205): luya\admin\proxy\ClientTransfer->start()
#6 [internal function]: luya\admin\commands\ProxyController->actionSync()
#7 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#9 /app/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('', Array)
#10 /app/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('', Array)
#11 /app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('admin/proxy', Array)
#12 /app/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('admin/proxy', Array)
#13 /app/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#14 /app/vendor/luyadev/luya-core/base/Boot.php(205): yii\base\Application->run()
#15 /app/vendor/luyadev/luya-core/bin/luya(22): luya\base\Boot->applicationConsole()
```

**Comment by boehsermoe** [comment]
While which table sync this happen?
Maybe the query will executed after a too long delay. Can you test it with higher wait_timeout? `SET GLOBAL wait_timeout 10;`
And maybe your env variables can be help:
`SHOW VARIABLES LIKE "max%";` and `SHOW VARIABLES LIKE "%timeout";`

**Comment by nadar** [comment]
It was an application table not related to the luya admin,cms project. Its very confusing as the problem appears only on the certain table, but its not even containing foreign key defintions...

the migration

```php
$this->createTable('th_email', [
            'id' => 'pk',
            'date' => 'varchar(80)',
            'subject' => 'varchar(80)',
            'from_name' => 'varchar(120)',
            'from_address' => 'varchar(120)',
            'to_string' => 'varchar(255)',
            'to_json' => 'text',
            'reply_to_json' => 'text',
            'message_id' => 'varchar(255)',
            'text_plain' => 'text',
            'text_html' => 'text',
            'attachements_json' => 'text',
            'user_id' => 'int(11)',
        ]);
```

the proxy command was running in a dockerized env.

**Comment by boehsermoe** [comment]
Could not reproduce this problem in my environment.
Will be the exception through also if you sync only this one table?
Will be the exception through also if you skip this table while the sync?
How many records contains the table and how long it needs?

**Comment by nadar** [comment]
today i had the same problem with another project, with a luya table

```
Fetch: admin_user_login [=======================================================>                        ] 68% (20/29) ETA: 7 sec.Exception 'yii\db\Exception' with message 'Error while sending QUERY packet. PID=5949
The SQL being executed was: SET FOREIGN_KEY_CHECKS = 1;'

in /vendor/yiisoft/yii2/db/Schema.php:664

Stack trace:
#0 /vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(yii\base\ErrorException), 'SET FOREIGN_KEY...')
#1 /vendor/yiisoft/yii2/db/Command.php(1075): yii\db\Command->internalExecute('SET FOREIGN_KEY...')
#2 /vendor/luyadev/luya-module-admin/src/proxy/ClientTable.php(181): yii\db\Command->execute()
#3 /vendor/luyadev/luya-module-admin/src/proxy/ClientTable.php(138): luya\admin\proxy\ClientTable->cleanup('ONLY_FULL_GROUP...')
#4 /vendor/luyadev/luya-module-admin/src/proxy/ClientTransfer.php(41): luya\admin\proxy\ClientTable->syncData()
#5 /vendor/luyadev/luya-module-admin/src/commands/ProxyController.php(205): luya\admin\proxy\ClientTransfer->start()
#6 [internal function]: luya\admin\commands\ProxyController->actionSync()
#7 /vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#9 /vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('', Array)
#10 /vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('', Array)
#11 /vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('admin/proxy', Array)
#12 /vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('admin/proxy', Array)
#13 /vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#14 /vendor/luyadev/luya-core/base/Boot.php(205): yii\base\Application->run()
#15 /vendor/luyadev/luya-core/bin/luya(22): luya\base\Boot->applicationConsole()
#16 {main}
```

**Comment by nadar** [comment]
So i did the proxy command again, and the exception was gone... :scream:

**Comment by boehsermoe** [comment]
But this happened while the admin_user_login tables was sync? Look like [syncDataInternal](https://github.com/luyadev/luya-module-admin/blob/master/src/proxy/ClientTable.php#L136) will throw an exception but the exception in the finally statement will "override" the previous exception.
 ```           
            $this->syncDataInternal();
        } finally {
            $this->cleanup($sqlMode);
        }
```

**Comment by nadar** [comment]
@boehsermoe would you like to send a PR?

**Comment by boehsermoe** [comment]
I will try to write some tests to replicate the problem and fix it.

**Comment by nadar** [comment]
this would be perfect! thanks

**Comment by boehsermoe** [comment]
I create a unit test for general exepction handling but I do not think it is the same problem what u had.

**Comment by nadar** [comment]
Maybe this problem appears when you are running a sync, while at the same time new data will be added.

**Comment by boehsermoe** [comment]
Looks like I could reproduce your exception finally 😅https://travis-ci.org/luyadev/luya-module-admin/jobs/517613614#L574-L576

**Comment by nadar** [comment]
So now we need to know how to fix 😄
