### ISSUE TITLE
pgsql migration error

### ISSUE THREAD

**Issue by nadar** [luyadev/luya-module-admin#609]
run migrate command 

```
.Exception: SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "index_identifier" already exists
The SQL being executed was: CREATE INDEX "index_identifier" ON "admin_storage_effect" ("identifier") (/workspace/vendor/yiisoft/yii2/db/Schema.php:678)
#0 /workspace/vendor/yiisoft/yii2/db/Command.php(1304): yii\db\Schema->convertException()
#1 /workspace/vendor/yiisoft/yii2/db/Command.php(1099): yii\db\Command->internalExecute()
#2 /workspace/vendor/yiisoft/yii2/db/Migration.php(495): yii\db\Command->execute()
#3 /workspace/vendor/luyadev/luya-module-admin/src/migrations/m180723_120432_indexes.php(48): yii\db\Migration->createIndex()
#4 /workspace/vendor/yiisoft/yii2/db/Migration.php(114): m180723_120432_indexes->safeUp()
#5 /workspace/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(744): yii\db\Migration->up()
#6 /workspace/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(202): yii\console\controllers\BaseMigrateController->migrateUp()
#7 [internal function]: yii\console\controllers\BaseMigrateController->actionUp()
#8 /workspace/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#9 /workspace/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#10 /workspace/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction()
#11 /workspace/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction()
#12 /workspace/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction()
#13 /workspace/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction()
#14 /workspace/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest()
#15 /workspace/vendor/luyadev/luya-core/base/Boot.php(251): yii\base\Application->run()
#16 /workspace/vendor/luyadev/luya-core/bin/luya(36): luya\base\Boot->applicationConsole()
#17 {main}
```

**Comment by nadar** [comment]
Fixes:

https://github.com/luyadev/luya-module-admin/commit/ecc33cf08fc0fc105f566ecfb429c72a89075d05
https://github.com/luyadev/luya-module-admin/commit/fd054d59d64e9eabd5fbfa143e49e8321cf104f0
https://github.com/luyadev/luya-module-admin/commit/4d7f2368ea3ed1794625461967a459aaf94acf11
https://github.com/luyadev/luya-module-admin/commit/26460479e93dfcd8ace0b6142c3759493403fd0f
https://github.com/luyadev/luya-module-admin/commit/dc1eec20f12bd9fedd7980d1675d3fb3367d0174
https://github.com/luyadev/luya-module-admin/commit/f43306580fc6db1dd722e0dfe380a63c696564d0
https://github.com/luyadev/luya-module-admin/commit/4f17abe2a66340da4232013d9227aa5be0518a82
https://github.com/luyadev/luya-module-admin/commit/50b636be0f1e926fcd5a10f06119d426957f60d3
https://github.com/luyadev/luya-module-admin/commit/a9d1232f55fe1a39a831ed9b7efe0ed08d365a86
