### ISSUE TITLE
Getting unknown property: luya\admin\models\User::login_attempt_lock_expiration

### ISSUE THREAD

**Issue by nick-denry** [luyadev/luya-module-admin#99]
Hi!

I want to review translations and I've updated my composer.json to get latest dev like that

```
"minimum-stability": "dev",
    "require": {
        "luyadev/luya-core" : "dev-master",
        "luyadev/luya-module-admin" : "dev-master",
        "luyadev/luya-module-cms" : "dev-master",
        "luyadev/luya-bootstrap3" : "dev-master",
        "luyadev/luya-generic" : "dev-master"
    },
```

Then I've got this error while trying to login:

```
Exception (Unknown Property) 'yii\base\UnknownPropertyException' with message 'Getting unknown property: luya\admin\models\User::login_attempt_lock_expiration' 

in /var/www/stends62/vendor/yiisoft/yii2/base/Component.php:154

Stack trace:
#0 /var/www/stends62/vendor/yiisoft/yii2/db/BaseActiveRecord.php(296): yii\base\Component->__get('login_attempt_l...')
#1 /var/www/stends62/vendor/luyadev/luya-module-admin/src/models/LoginForm.php(98): yii\db\BaseActiveRecord->__get('login_attempt_l...')
#2 /var/www/stends62/vendor/luyadev/luya-module-admin/src/models/LoginForm.php(83): luya\admin\models\LoginForm->userAttemptBruteForceLockHasExceeded(Object(luya\admin\models\User))
#3 /var/www/stends62/vendor/luyadev/luya-module-admin/src/models/LoginForm.php(67): luya\admin\models\LoginForm->userAttemptBruteForceLock(Object(luya\admin\models\User))
#4 [internal function]: luya\admin\models\LoginForm->validatePassword('password', NULL, Object(yii\validators\InlineValidator))
#5 /var/www/stends62/vendor/yiisoft/yii2/validators/InlineValidator.php(72): call_user_func(Array, 'password', NULL, Object(yii\validators\InlineValidator))
#6 /var/www/stends62/vendor/yiisoft/yii2/validators/Validator.php(267): yii\validators\InlineValidator->validateAttribute(Object(luya\admin\models\LoginForm), 'password')
#7 /var/www/stends62/vendor/yiisoft/yii2/base/Model.php(367): yii\validators\Validator->validateAttributes(Object(luya\admin\models\LoginForm), Array)
#8 /var/www/stends62/vendor/luyadev/luya-module-admin/src/models/LoginForm.php(158): yii\base\Model->validate()
#9 /var/www/stends62/vendor/luyadev/luya-module-admin/src/controllers/LoginController.php(98): luya\admin\models\LoginForm->login()
#10 [internal function]: luya\admin\controllers\LoginController->actionAsync()
#11 /var/www/stends62/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /var/www/stends62/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#13 /var/www/stends62/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('async', Array)
#14 /var/www/stends62/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('admin/login/asy...', Array)
#15 /var/www/stends62/vendor/luyadev/luya-core/web/Application.php(47): yii\web\Application->handleRequest(Object(luya\web\Request))
#16 /var/www/stends62/vendor/yiisoft/yii2/base/Application.php(386): luya\web\Application->handleRequest(Object(luya\web\Request))
#17 /var/www/stends62/vendor/luyadev/luya-core/base/Boot.php(221): yii\base\Application->run()
#18 /var/www/stends62/vendor/luyadev/luya-core/base/Boot.php(165): luya\base\Boot->applicationWeb()
#19 /var/www/stends62/public_html/index.php(8): luya\base\Boot->run()
#20 {main}
```

So can't login in

**Comment by nadar** [comment]
Yes 1.2 has new migrations therefore run migrate command

Nick Denry <notifications@github.com> schrieb am So., 15. Apr. 2018, 23:20:

**Comment by nick-denry** [comment]
Thanks.
